### ISSUE TITLE
Content body not as JSON does not get transferred (e.g.: application/x-www-form-urlencoded)

### ISSUE THREAD

**Issue by Nordes** [probot/smee.io#11]
Hi,

When I try to send data as `application/x-www-form-urlencoded`, it does not forward it to the event client => my app.

I think it's because right now smee.io only consider content-type JSON (body).

It would be a nice addition to also have the `x-www-form-urlencoded` in order to integrate with slack bot/commands.

I didn't try it, but in https://github.com/probot/smee.io/blob/master/server.js#L32 you add the JSON option. But after you can also add `app.use(express.urlencoded())` in order to transform the encoded form url into the body as json payload.

**Comment by Nordes** [comment]
A pull request have been created. 

> https://github.com/probot/smee.io/pull/13

**Comment by yoavtzelnick** [comment]
Running into the same problem

**Comment by jquick** [comment]
This would be really helpful

**Comment by edwardbadboy** [comment]
Affected by the same problem.

**Comment by JasonEtco** [comment]
Closed by #13
