### ISSUE TITLE
smee channels seems to be down

### ISSUE THREAD

**Issue by thomasmebin** [probot/smee.io#122]
Hi Team,

I am using smee for my GH app development, and starting from yesterday, the channel is not working as expected, its seems to be down most of the time.

![image](https://user-images.githubusercontent.com/77664686/197953866-ed816bdb-75d7-4b87-b495-7adb61be0b0b.png)

Sometime, getting 502 upstream error, sometime channel showing, but payload not able to delivering and sometime channel is not opening.

![image](https://user-images.githubusercontent.com/77664686/197955078-e8035877-e215-4c2f-bb8a-38be9f088e26.png)

![image](https://user-images.githubusercontent.com/77664686/197954566-cf4c837c-b7f3-47b2-ab0f-aae7e8861e58.png)

Can anyone support me in this situation ??

Regards,
Mebin Thomas

**Comment by fabriziogianni7** [comment]
yes, confirm. smee stopped working

**Comment by eddyfrank** [comment]
My private projects were also affected, and I was aware of this:

> Should I use this in production?
> No! Smee is not designed for production use - it is a development and testing tool....

https://github.com/probot/smee.io#faq


I suggest setting up your own server:
1) Get a $6 bucks cloud instance (e.g from https://www.digitalocean.com)
2) Clone this repo and run `npm start` :)

Or alternatively, use your existing server and run a docker:
https://github.com/probot/smee.io#deploying-your-own-smeeio

Nonetheless, smee is a great tool. Thanks and kudos to the Probot guys.
