### ISSUE TITLE
Allow linking to event

### ISSUE THREAD

**Issue by atsu85** [probot/smee.io#156]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to be able to share link to specific event. My specific use-case is generating link to the event in Smee UI from code when event is received, so event payload could be easily inspected.

**Describe the solution you'd like**
Allow linking to event in smee ui, for example using query parameter after channel name: `?eventId=a73d1756-d5e5-4b9b-98a0-b078b0f8c033`

**Describe alternatives you've considered**
I don't have clear alternative for my specific use-case. It is usually easy to find the latest event from UI, but harder for old events (i.e. based on logs for further investigation) or if there are lots of events. Maybe existing filtering syntax also allows finding the event by id, but that would be much less convenient than being able to deep-link to specific event.

**Teachability, Documentation, Adoption, Migration Strategy**
From UI perspective, it would be nice if the UI added link sharing button (i'm not proposing nice icon myself, just indicating the button location with text):
![image](https://github.com/probot/probot/assets/1206512/9fb0f07d-6162-4407-bc4b-7117b0f7f0f1)

**Comment by Uzlopak** [comment]
This is simply not possible. smee.io does not store the events in any database. You either receive the webhook call in smee.io or you dont. If you receive it, it is stored in the browser in the localstorage. 

You can test it, by running a webhook against a smee.io channel and then open in inkognito mode or a different browser the same channel. You will see an empty channel. 

So to share something you need it persisted somewhere. As there is nothing persisted, there is nothing to share.

**Comment by atsu85** [comment]
ok, thanks for explaining - feel free to rename & close this ticket as you see fit
