### ISSUE TITLE
smee blocks * origin for CORS preflight request

### ISSUE THREAD

**Issue by rvantonder** [probot/smee.io#2]
smee is set up to allow all CORS origins here:
https://github.com/probot/smee/blob/master/server/server.js#L75

but it rejects CORS preflight requests (cf CORS spec). Smee will therefore block servers or connections that expect the preflight request to pass before issuing further requests. To remedy, smee should respond with the correct headers to an `OPTIONS` method for preflight requests. 

Example:

`curl -i -X OPTIONS localhost:3000`

currently gives

```
HTTP/1.1 200 OK
X-Powered-By: Express
Allow: GET,HEAD
Content-Type: text/html; charset=utf-8
Content-Length: 8
ETag: W/"8-ZRAf8oNBS3Bjb/SU2GYZCmbtmXg"
Date: Tue, 18 Dec 2018 22:42:29 GMT
Connection: keep-alive

GET,HEAD
```

The preflight response should include the headers 

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
```

**Comment by nirvdrum** [comment]
As of 16-Nov-2019, this issue is still relevant. As far as I can tell, smee.io doesn't respond to the `OPTIONS` HTTP method and as such, preflight CORS requests are blocked.
