### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by ahmadnassri** [probot/smee.io#4]
seems like whatever proxy service smee is using blocks large payloads from GitHub.

![image](https://user-images.githubusercontent.com/183195/52542747-00d4a100-2d71-11e9-9a8e-3d80483443a2.png)

the above webhook does not register in the smee interface, nor does it hit my downstream server

**Comment by sonukr2208** [comment]
Any update on this issue, I am getting same issue when we merged develop into master for release. As there were around 140 commit getting merged to master it was unable to deliver the payload.

![Capture](https://user-images.githubusercontent.com/6467148/75699502-95f94f00-5c7e-11ea-93ef-5bf761da244e.PNG)

**Comment by JasonEtco** [comment]
I don’t have an update to give, this isn’t something we’ve taken steps to solve. I’ll give my thoughts though:

Smee is not designed or intended for production use, it’s a tool for development. This means that functionality that depends on certain scaling features is implicitly not supported. It looks like these payloads are generated for real, “production” events - I wonder if that’s something that should be done against development Probot apps.

A typical pattern is to have separate GitHub Apps for prod and dev, sharing the same codebase with different credentials. That would help build the app without depending on development tools.

I hope that makes sense. To be clear, my hesitation with changing Express’ default is to avoid an abuse vector for any Smee event. We can do some filtering but I personally don’t feel that it’s necessary.

**Comment by sonukr2208** [comment]
I understand smee is not for production use, but I would not define my setup as prod. I followed this article https://jenkins.io/blog/2019/01/07/webhook-firewalls/ to setup build invocation as our Jenkins server lives within firewall. And we noticed that we get `payload too Large` error during release cycle as we merge develop to master branch.

I will look for some other option. Thanks for your input and thoughts.

**Comment by JasonEtco** [comment]
I'm going to close this out because I don't think there's any action we should take here. Smee is not intended for production use, and being a proxy for a "production" Jenkins server behind a firewall kind of goes against that. Keep in mind that limits like this are for abuse protection, so while the large payloads from this issue are valid, they're also way bigger than 99% of payloads that go through Smee. Thanks all for the conversation and patience 🙏
