### ISSUE TITLE
Docker build needs python

### ISSUE THREAD

**Issue by benzman81** [probot/smee.io#50]
The docker build of the current Dockerfile does not work anymore because python is required.
Adding `RUN apk add --no-cache make gcc g++ python`  brefore `RUN npm ci` fixes the issue.

**Comment by JasonEtco** [comment]
👋 Python isn't actually needed, `npm ci` throws errors from optional dependencies, all used for local development. We can't only install production dependencies, because that would prevent us from building the front-end bundles. So - this can be safely ignored 👍

**Comment by benzman81** [comment]
for me, a docker build wasnt possible. Now, with your changes in Dockerfile for #51 the build is working.
