### ISSUE TITLE
Docker build does not build with webpack

### ISSUE THREAD

**Issue by benzman81** [probot/smee.io#51]
Since switching to `npm ci` in Dockerfile the comman `webpack -p` is not called anymore so the files `main.min.css` and `main.min.js` are mssing in the builded image. Switching back to `npm install --unsafe-perm` fixes this issue. Maybe there is some more changes to do to use `npm ci`.

**Comment by JasonEtco** [comment]
Closed by #52, thanks for the issue!

**Comment by benzman81** [comment]
Now, docker build is working as expected and builds a fully functional smee.io. Thanks for fixing.
