### ISSUE TITLE
Convert paddle webhooks to use smee

### ISSUE THREAD

**Issue by honestbonsai** [probot/smee.io#54]
https://github.com/probot/smee.io/pull/13 got merged recently, which means we can use smee with Paddle

- [ ] Convert existing paddle stuff to use it
- [ ] Add a env field to paddle passthrough so multiple devs can use the webhooks

**Comment by JasonEtco** [comment]
👋 I don’t think you meant to open this issue here - but it doesn’t look like there’s a question or action item for Smee, so I’m going to close it. Feel free to reopen if I’m mistaken!

**Comment by honestbonsai** [comment]
Haha sorry about that! Thanks for closing it.

**Comment by JasonEtco** [comment]
All good, been there 😄
