### ISSUE TITLE
Can't send custom statuses

### ISSUE THREAD

**Issue by Xenfo** [probot/smee.io#58]
So I've been trying to send code 500 to my Github webhook all day but when I would check Github said it received code 200. Sure enough when I peak at the source code of Smee code 200 is hardcoded in as the only code.

Is it possible to make it so that users can send custom responses to the server. I love Smee because I don't have to change the hook url every time I want to code but with other options like Ngrok I could easily do this. I would much appreciate this feature being added...

**Comment by cody-elhard** [comment]
Any updates on this? My service wants a 204 response preventing me from developing with smee

Should we just fork the project?
