### ISSUE TITLE
smee.io Service Unavailable

### ISSUE THREAD

**Issue by lelelelelez** [probot/smee.io#64]
![image](https://user-images.githubusercontent.com/22937122/113822419-ff1b9200-97af-11eb-98a9-ce90f3f24402.png)
![image](https://user-images.githubusercontent.com/22937122/113822469-0c388100-97b0-11eb-8b6e-6599d3c2f652.png)
![image](https://user-images.githubusercontent.com/22937122/113822554-27a38c00-97b0-11eb-8e91-9d5f6cb97f80.png)

**Comment by gr2m** [comment]
I don't have access to the server myself, but I pinged some folks. Unfortunately is night time for both of them, so it might take a while until someone can look into it
