### ISSUE TITLE
Run in detached mode 🔗

### ISSUE THREAD

**Issue by jessicafarias** [probot/smee.io#73]
In order to avoid to keep the terminal open and to have multiple paths listening.
I was wondering if you can implement a -d option to keep run and listening witouth having a terminal open in detached mode or in the background from terminal. And also a way to check all running process in smee such as docker does with -d and ps.
where:  d=detach and ps=process status

```
user@user:~$ smee -d
Forwarding https://smee.io/1PUc3ipJCAKIMTaR to http://127.0.0.1:3000/
Connected https://smee.io/1PUc3ipJCAKIMTaR
Detached

user@user:~$ smee ps
URL                                     PATH      PORT
https://smee.io/1PUc3ipJCAKIMTaR         /        3000
```
OR:
```
user@user:~$ smee -d -u https://smee.io/new -P /custom_path/ -p 8080
Forwarding https://smee.io/new to http://127.0.0.1:8080/custom_path
Connected https://smee.io/new
Detached

user@user:~$ smee ps
URL                         PATH                PORT
https://smee.io/new         /custom_path        8080
```

**Comment by gr2m** [comment]
Hey Jessica, I wouldn't mind that, but isn't that something you can do with built-in unix tools, without the necessity to add support for a `-d` flag? I'm no expert, just wondering. 

What would it entail to add the `-d` flag? I've never implemented such a feature before

**Comment by jessicafarias** [comment]
I'm not sure, I found something similar here:
https://www.tecmint.com/run-linux-command-process-in-background-detach-process/ 

where you can use the & on linux
```
jessica@jessica:~$ smee &
Forwarding https://smee.io/99hqrIEtrRkb0B8y to http://127.0.0.1:3000/
hConnected https://smee.io/99hqrIEtrRkb0B8y
[1]+  Running              smee &

jessica@jessica:~$ smee -u https://smee.io/new -P /custom_path/ -p 8080 &
[2]+  Running              smee ... &

jessica@jessica:~$ jobs
[1]+  Running              smee &
[2]+  Running              smee ... &
```

I'm already tested and I almost got the same result, I can keep more than 1 path listening in just one terminal, but when I close the terminal the "jobs" finished.

**Comment by gr2m** [comment]
do you want the `smee` process to run in the background, even if you close the terminal window? I don't feel like this is within the scope of the smee cli, I think the different operating systems have their own tooling to achieve that, e.g. running the process as a daemon on unix systems?

**Comment by jessicafarias** [comment]
I got confused with this repo and [smee-client](https://github.com/probot/smee-client) repo. 
But you're right I can get the same result with [smee-client](https://github.com/probot/smee-client) and create a daemon on unix systems. 

Thanks @gr2m !
