### ISSUE TITLE
[DISCUSSION] Support for methods other than POST?

### ISSUE THREAD

**Issue by ddouglas** [probot/smee.io#77]
I understand that smee is a webhook payload forwarding service, but is there any way the rest of the basic HTTP Methods for CRUD Actions (GET, PUT, PATCH, DELETE) could be implemented.

I have more ideas on this, but I'm interested to hear feedback first.

I'm aware that `GET /:channel` renders the very helpful UI. This could be hosted on `GET /ui/:channel` which frees up GET requests to be forwarded on `/:channel`

**Comment by Chocrates** [comment]
Would love this as well, we could use this as a generic proxy for development.

**Comment by wolfy1339** [comment]
Smee.io is only for forwarding webhooks for developement.

Smee uses Server Side Envents to forward the Webhooks to your local application.

I can't see how that would work for regular HTTP requets.
