### ISSUE TITLE
Error that certificate has expired

### ISSUE THREAD

**Issue by aleksandar-stefanovic-tamedia** [probot/smee.io#82]
I was using smee for a year but from a last week I'm getting error: Event { type: 'error', message: 'certificate has expired' }
Smee as service is started inside Jenkins instance but I have no idea which certificate has expired. Can someone help me with this issue?

**Comment by Jdwoodson** [comment]
I also am having this issue. :(

Any help pointing in the right direction would be much much appreciated. We've even gone and created a new URL and adjusted our webhooks in attempts to "start anew" and that did not resolve the issue.

**Comment by aleksandar-stefanovic-tamedia** [comment]
I manage to solve problem on our Jenkins. Problem was with root CA certificate from Java within Jenkins. It was Java 8. We upgraded Java 8 to Java 11 and the problem was solved.

**Comment by tcbyrd** [comment]
Do y'all have any suggestions on whether we could improve anything with the server to help point people in the right direction here when they see this error? Otherwise I think we're good to close this issue.

**Comment by aleksandar-stefanovic-tamedia** [comment]
We can close it.
