### ISSUE TITLE
duplicate deliveries

### ISSUE THREAD

**Issue by jeffmcaffer** [probot/smee.io#89]
I seem to be getting duplicate deliveries from a channel on smee.io. I have a simple test that repros it for me. See attached. 

1. get the zip, unzip, run npm install and update the channel URL to one of yours
2. run `node index.js`
3. Open your channel on smee.io
3. Trigger events in GitHub. For me, I've been editing an issue comment.
4. Observe that multiple (two in my case) entries are output on the console for each event triggered on GitHub.
5. flip over to smee.io and redeliver the event. Notice that only one entry is output.

I don't see anything I'm doing wrong in my code and AFAICT this is a relatively recent behavior (whereas this code has been running for several months).  I'm thinking its smee because 
* in the UI only one event is shown. That is, GitHub is only delivering once to smee
* if I resend the event from the smee UI, I get just one in my app
* if I do the action in the GitHub UI, I get two in my app and smee.io's UI correctly shows just one. 

I've checked all my machines and do not appear to have any other clients running.  Any next steps I can do for debugging this?

[smeetest.zip](https://github.com/probot/smee.io/files/7979863/smeetest.zip)

**Comment by jeffmcaffer** [comment]
Update. I created a new channel and all is well. It seems like somehow the channel I was using got in a state where smee thought it should deliver twice.  Is there a scenario where that would be "a good thing"?

**Comment by tcbyrd** [comment]
Not that I can think of. It emits the even to anything listening on that EventBus, but the behavior your describe definitely sounds like it wasn't two clients, but two instances of `send()` being called at the same time. My hunch is the connection didn't close properly, resulting in it delivering to the same client twice. We could probably benefit from displaying more of the state of the connections in the UI. That would at least help with debugging these types of issues in the future.

I checked out your code. Nothing looks weird there. I'll close the issue, but LMK if it crops up again.

**Comment by rrotaru** [comment]
I was able to recreate this by having smee-client installed twice: once globally via `npm install -g smee-client` and once via a local install to the project's `node_modules/` directory.

When I had two copies of smee-client installed, running `smee` resulted in two copies of payloads being delivered. Once I uninstalled one and restarted the client, the behavior went back to normal. I reinstalled it just to confirm and the duplicate payloads returned.

@jeffmcaffer can you confirm whether you possibly had it installed twice when this issue was happening?

**Comment by jeffmcaffer** [comment]
Interesting. I don't appear to have it installed globally. Also, I "fixed" my problem by generating a new channel so no code or setup changes.
